version: "3.1"

services:
  watch:
    image: api:local
    hostname: api
    volumes:
      - ./src:/app/src:ro
      - ./migrations:/app/migrations:ro
      - ./import_map.json:/app/import_map.json:ro
      - ./deps_lock.json:/app/deps_lock.json:ro
    ports:
      - 1337:1337
    command: "run --watch -A --importmap import_map.json ./src/index.ts"
    env_file:
      - .env
    depends_on:
      - postgres
      - adminer # its optional, but good for development

  api:
    image: api:local
    hostname: api
    volumes:
      - ./src:/app/src:ro
      - ./migrations:/app/migrations:ro
      - ./import_map.json:/app/import_map.json:ro
      - ./deps_lock.json:/app/deps_lock.json:ro
    ports:
      - 1337:1337
    command: "run -A --importmap import_map.json ./src/index.ts"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    hostname: adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  db:
